version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/bmgn
    networks:
      - bmgn
      - nginx-load-balancer
    restart: always
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
networks:
  bmgn:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
